### ISSUE TITLE
Pagination last hat unten keinen Border

### ISSUE THREAD

**Issue by Aybee** [contao/official-demo#12]
Der Border unten ist zwar explizit entfernt worden, ich weiß aber nicht warum, sieht auf jeden Fall falsch aus.

``` css
.mod_search .last {
  border-bottom: medium none;
}
```

Gesehen auf search.html Suche nach contao.
