### ISSUE TITLE
Optische Optimierung der COD - Deine Meinung zählt

### ISSUE THREAD

**Issue by may17** [contao/official-demo#38]
Ich möchte ganz gerne ein paar Ideen und Anregungen von euch sammeln. Was stört euch optisch und wie könnte es eurer Meinung nach besser sein?

Wir sind sehr gespannt und freuen uns über Input.

**Comment by ciaobello** [comment]
Danke Joe für die Anpassungen. Ich habe den Aktuellen Release mit einer 3.4.3 Version und dem Composer getestet. Hat alles einwandfrei geklappt bei der Installation.
Das angepasste Outfitt macht schon einen ganz anderen Eindruck. Auch das mit den Ergänzten Fabvariabeln sieht vielversprechend aus.

Danke für Deine Arbeit!!

**Comment by may17** [comment]
Danke @ciaobello für das Feedback. Es wird nun wieder konsequenter an der Demo gearbeitet. Generell bin ich mit dem Optik noch unzufrieden aber wir sind auf dem richtigen Weg. Danke für dein Support!

**Comment by Aybee** [comment]
Ich kann da keine farblichen Änderungen sehen. Mache ich irgendetwas falsch? Ich habe official-demo-3.4.1 herunter geladen, Resourcen auf den Server gelegt. Im Install tool die SQL importiert (kein Haken gesetzt).

Auch mit official-demo-master, official-demo-develop oder official-demo-release-contao35x sehe ich kein anderes Farbschema.

**Comment by ciaobello** [comment]
@Aybee, du musst die Variabeln selber anpassen mit den Farben wie Du sie haben willst. Es gibt bei den Einstellungen des Themes einen Ganzen Rattenschwanz an Variabeln welche mit dem Internen CSS Editor verbunden sind (Tabelle tl_themes; Feld vars):

"$basecolor";"60584D"
"$darkercolor";"5d2f00"
"$footerColor";"473F3A"
"$footerTextcolor";"9E9084"
"$baseBorderColor";"D4CBC5"
"$wrapperBgColor";"FBFAF9"
"$footerLinkcolor";"ffffff"
"$footerBordercolor";"60584D"
"$highlightcolor";"E37A25"
"$bgColor";"BEB1A9"
"$navOffColor";"7F7266"
"$navOffBorder";"D4CBC5"
"$navOffGradient1";"F4F2F0"
"$navOffGradient2";"EEE9E7"
"$navOffGradient3";"E1DAD6"
"$navHoverBg";"F4F2F0"
"$navHoverBorder";"E5DFDC"
"$navOnColor";"ffffff"
"$navOnBorder";"DE601A"
"$navOnGradient1";"FF9B50"
"$navOnGradient2";"E37A25"
"$navOnGradient3";"E37A25"
"$navOnGradient4";"DE601A"
"$navSubBorderTop";"eeeeee"
"$navSubItemBorderTop";"ffffff"
"$navSubItemBorderBottom";"E5DFDC"
"$box1Bg";"EEE9E7"
"$box2Bg";"F4F2F0"
"$tableHeadBg";"eee9e7"
"$tableEvenBg";"f4f2f0"
"$tableOddBg";"F6F6F6"
"$topbarBg";"eae5e2"
"$inputOffBg";"F4F2F0"
"$inputOnBg";"fdfdfd"
"$errorColor";"c20000"

**Comment by Aybee** [comment]
@ciaobello Danke. Ja, die Variablen hatte ich gesehen, aber es hörte sich hier so an, als hätte bereits jemand ein Farbschema ausgearbeitet.

Ich habe mal nur zum Spaß auf wissenschaftlicher Helligkeitsanalyse die Variablen in Grauwerte verwandelt :smirk: 
```xml
<field name="vars">
a:35:{i:0;a:2:{s:3:"key";s:10:"$basecolor";s:5:"value";s:6:"595959";}i:1;a:2:{s:3:"key";s:12:"$darkercolor";s:5:"value";s:6:"3C3C3C";}i:2;a:2:{s:3:"key";s:12:"$footerColor";s:5:"value";s:6:"404040";}i:3;a:2:{s:3:"key";s:16:"$footerTextcolor";s:5:"value";s:6:"929292";}i:4;a:2:{s:3:"key";s:16:"$baseBorderColor";s:5:"value";s:3:"CCC";}i:5;a:2:{s:3:"key";s:15:"$wrapperBgColor";s:5:"value";s:6:"FAFAFA";}i:6;a:2:{s:3:"key";s:16:"$footerLinkcolor";s:5:"value";s:3:"FFF";}i:7;a:2:{s:3:"key";s:18:"$footerBordercolor";s:5:"value";s:6:"595959";}i:8;a:2:{s:3:"key";s:15:"$highlightcolor";s:5:"value";s:6:"969696";}i:9;a:2:{s:3:"key";s:8:"$bgColor";s:5:"value";s:6:"B3B3B3";}i:10;a:2:{s:3:"key";s:12:"$navOffColor";s:5:"value";s:6:"747474";}i:11;a:2:{s:3:"key";s:13:"$navOffBorder";s:5:"value";s:3:"CCC";}i:12;a:2:{s:3:"key";s:16:"$navOffGradient1";s:5:"value";s:6:"F2F2F2";}i:13;a:2:{s:3:"key";s:16:"$navOffGradient2";s:5:"value";s:6:"EAEAEA";}i:14;a:2:{s:3:"key";s:16:"$navOffGradient3";s:5:"value";s:6:"DBDBDB";}i:15;a:2:{s:3:"key";s:11:"$navHoverBg";s:5:"value";s:6:"F2F2F2";}i:16;a:2:{s:3:"key";s:15:"$navHoverBorder";s:5:"value";s:6:"E0E0E0";}i:17;a:2:{s:3:"key";s:11:"$navOnColor";s:5:"value";s:3:"FFF";}i:18;a:2:{s:3:"key";s:12:"$navOnBorder";s:5:"value";s:6:"878787";}i:19;a:2:{s:3:"key";s:15:"$navOnGradient1";s:5:"value";s:6:"B4B4B4";}i:20;a:2:{s:3:"key";s:15:"$navOnGradient2";s:5:"value";s:6:"969696";}i:21;a:2:{s:3:"key";s:15:"$navOnGradient3";s:5:"value";s:6:"969696";}i:22;a:2:{s:3:"key";s:15:"$navOnGradient4";s:5:"value";s:6:"878787";}i:23;a:2:{s:3:"key";s:16:"$navSubBorderTop";s:5:"value";s:3:"EEE";}i:24;a:2:{s:3:"key";s:20:"$navSubItemBorderTop";s:5:"value";s:3:"FFF";}i:25;a:2:{s:3:"key";s:23:"$navSubItemBorderBottom";s:5:"value";s:6:"E0E0E0";}i:26;a:2:{s:3:"key";s:7:"$box1Bg";s:5:"value";s:6:"EAEAEA";}i:27;a:2:{s:3:"key";s:7:"$box2Bg";s:5:"value";s:6:"F2F2F2";}i:28;a:2:{s:3:"key";s:12:"$tableHeadBg";s:5:"value";s:6:"EAEAEA";}i:29;a:2:{s:3:"key";s:12:"$tableEvenBg";s:5:"value";s:6:"F2F2F2";}i:30;a:2:{s:3:"key";s:11:"$tableOddBg";s:5:"value";s:6:"F6F6F6";}i:31;a:2:{s:3:"key";s:9:"$topbarBg";s:5:"value";s:6:"E6E6E6";}i:32;a:2:{s:3:"key";s:11:"$inputOffBg";s:5:"value";s:6:"F2F2F2";}i:33;a:2:{s:3:"key";s:10:"$inputOnBg";s:5:"value";s:6:"FDFDFD";}i:34;a:2:{s:3:"key";s:11:"$errorColor";s:5:"value";s:6:"c20000";}}
</field>

```
Ich habe auch mal ein kleines BE-Javascript implementiert, welches den Hintergrund des Feldes einer Farbvariablen mit der eingestellten Farbe belegt und die Schriftfarbe dieses Feldes je nachdem auf weiß oder schwarz setzt. Damit kann man besser mit den Farben experimentieren. Falls das jemand haben möchte. Ich denke hier kann man keine Dateien hochladen, oder?

**Comment by ciaobello** [comment]
@Aybee Github und Daten Hochladen ist so eine Sache ... Gist wäre die Alternative aber sehe gerade dass da auch schon wieder was geändert hat. Gibt doch Seiten wo man .js Dateien hochladen kann, dessen Quellcode angezeigt wird und auf der rechten Seite das Resultat siehst ... Ich bin ein bisschen vergesslich mit den Namen solchen Services da ich die nicht wirklich brauche ... 

Vielleicht machst schnell ein Wiki Artikel wo das Skript rein packen kannst ?! und Verlinkst den hier.

Ich bin mit dem Forum & Wort COD vorsichtig geworden. Das ist wie ein Schimpfwort welches die "U-boot warriors" heraufbeschwört welche erst bei geschlossenen Themen wieder abtauchen ... das lassen wir besser sein :P

**Comment by may17** [comment]
@ciaobello  du meinst jsbin oder jsfiddle ;)

>Ich bin mit dem Forum & Wort COD vorsichtig geworden. Das ist wie ein Schimpfwort welches die "U-boot warriors" heraufbeschwört welche erst bei geschlossenen Themen wieder abtauchen ... das lassen wir besser sein :P

Hast du mal Beispiele. Würde mich ja mal interessieren :)

**Comment by may17** [comment]
btw. so schlecht kann die Contao Demo ja nicht sein denn sie wird scheinbar oft genutzt :)

http://www.tv-niebelsbach.de/
http://www.rv-bamlach.de/
http://www.schwarzehusaren.de/
http://www.luisenhof-gemeinschaft.de/
http://www.schmerzordination.at/
http://www.forum-spirituale.de/
http://felice-hn.de/
http://www.psychotherapie-fauser.de/
http://www.nordsee-diefenbach.de/
http://www.carbon-pools.at/
http://www.conference712.com/en/

**Comment by ciaobello** [comment]
Ja genau die meinte ich.

Hey, du hast das falsch verstanden. Ich habe nichts gesagt dass die nicht gut ist. Nur das Cod / ma2 thema welches geschlossen wurde war eine ziemliche Schlammschlacht. Davor hüte ich mich ... Und von den U-Broten in diesem Thema habe ich gesprochen.

Trotzdem Danke für die tolle Referenzliste  : )

**Comment by may17** [comment]
Sorry das wollte ich damit auch nicht sagen. Schon richtig, dass die Disskusion im Forum ausgeartet ist ich denke so langsam haben sich aber da die wogen geglättet denke ich.

**Comment by ciaobello** [comment]
Zurück zum Thema, ich habe mir überlegt ob man bei den Variabeln in Themes nicht noch zwei weitere Felder einfügen könnte (jetzt gibt es ja nur zwei). Eines welches "Gruppieren" heißt und das andere welches z.Bsp. "Optik" heißt. Bei den Farben würde dass die Farbe selber anzeigen.

So könnte man die Variabeln in Gruppen aufteilen und nach Farben/Farbtönen anordnen. Mit dem Optischen Hinweis würde dass eine große Hilfe sein.

Ich wollte das im Core vorschlagen, aber ich finde die Stelle nicht, welche ich Referenzieren müsste? Die Tabelle die es im Backend bei den Variabeln anzeigt?

**Comment by Aybee** [comment]
Ich glaube ich mache da keinen Wiki-Artikel, weil es ja eigentlich mit PHP gemacht werden müsste und ich es nur eben quick mit JS gemacht habe. Weil's doch nicht so viel ist, habe ich es jetzt  einfach mal hier rein gepackt.
system/dcaconfig.php
```php
// some extra BE CSS and JS
if(TL_MODE == 'BE')
{
  $GLOBALS['TL_CSS'][]      = 'files/css/_my_be.css';
  $GLOBALS['TL_MOOTOOLS'][] = '<script src="files/js/_my_be.js"></script>';
}
```
files/css/_my_be.css
```css
.monospace {
  font-family: consolas, courier, monospace;
}
```
files/js/_my_be.js
```javascript
(function($) {
  window.addEvent('domready', function() {

    var
      themeGlobalVars = $$('#pal_vars_legend td:nth-child(2) input') || false,
      inputVar, isHex6, isHex3, t, bigInt, r, g, b, brightness, textCol
    ;

    // Format global theme variables
    if(themeGlobalVars){
      Array.each(themeGlobalVars, function(item){
        inputVar = item.value;

        isHex6 = /(^[A-F\d]{6}$)/i.test(inputVar);

        if(!isHex6){
          isHex3 = /(^[A-F\d]{3}$)/i.test(inputVar);

          if(isHex3){
            t = inputVar.split('');
            inputVar = t[0] + t[0] + t[1] + t[1] + t[2] + t[2];
          }
        }

        if(isHex3 || isHex6){
          bigint = parseInt(inputVar, 16);
          r = (bigint >> 16) & 255;
          g = (bigint >> 8) & 255;
          b = bigint & 255;

          brightness  = (0.2126 * r) + (0.7152 * g) + (0.0722 * b);

          textCol = (brightness < 127) ? '#fff' : '#000';

          item.style.color = textCol;
          item.style.backgroundColor = '#' + inputVar;
        }
      });

      $$('#pal_vars_legend input').addClass('monospace');
    }

  });
})(document.id);
```

**Comment by Aybee** [comment]
> Ich wollte das im Core vorschlagen, aber ich finde die Stelle nicht, welche ich Referenzieren müsste? Die Tabelle die es im Backend bei den Variabeln anzeigt?
Die Tabelle wird aus einem Feld aufgebaut tl_theme-vars
Der Wert ist serialisiert.

**Comment by ciaobello** [comment]
dann vermutlich in einer be_vorlage? Denn ich konnte nirgens ein php skript finden.

**Comment by ciaobello** [comment]
@Aybee, danke für das js, sieht toll aus. Es vereinfacht das arbeiten wesentlich. Danke.

**Comment by Aybee** [comment]
@ciaobello danke, gerne, habe ich mir auch gedacht
> dann vermutlich in einer be_vorlage? Denn ich konnte nirgens ein php skript finden.

Das Feld wird in system/modules/core/dca/tl_theme.php konfiguriert, und ist vom Typ keyValueWizard

Ich kenne mich mit dem Feld nicht aus. Sieht so aus, als könne man damit nur einen key und einen value generieren, also 2 Felder. https://github.com/contao/core/blob/master/system/modules/core/widgets/KeyValueWizard.php

**Comment by may17** [comment]
Warum machst du nicht einfach ein Modul?

**Comment by ciaobello** [comment]
Ich habe es mit einem Modul versucht. Habe aber noch nicht herausgefunden wie der Aufbau sein soll ... resp. die Folderstruktur und wo die Config rein soll, ob ich die Files auch in das systems/modules packen soll. Ist Vendor ev. sinnvoller?

**Comment by Aybee** [comment]
Geht es um das, was ich gepostet hatte? Dann würde ich die files nach myModule/assets/ packen. Und den Rest in die myModule/config/config.php. Oder?

http://public.andreasburg.de/myBE.zip

**Comment by ciaobello** [comment]
Danke hat geklappt.

**Comment by ciaobello** [comment]
Ich bin dran bei der 3.2er Version die Steuerelemente (Grafiken) zu entfernen und diese Durch passende FontAwesome Symbole zu ersetzen, damit diese auch farblich mit den Variabeln angepasst werden können. Die Toggler vom Accordeon konnte ich schon anpassen:
(Erweiterung  font-awesome  >Netzmacht)

Noch nicht bereinigte Klassen (in css ce):

```css
inside active
.toggler.ui-state-active:after {
    float:right;
    display:inline-block;
    font:20px FontAwesome;;
    text-indent: 8px;
    fontcolor: $basecolor;
    content:"\f139"
}

.toggler:after {
    width:20px;
    height:20px;
    min-height:20px;
    right:10px;
    float:right;
    display:inline-block;
    background-position:center center;
    background-repeat:no-repeat;
    font:20px FontAwesome;;
    font-weight:bold;
    text-indent:-9999em;
    text-indent: 8px;
    content: "\f13a";
    fontcolor: $basecolor;
}
```
Für die Suche (Lupe) und das RSS Icon könnte man dies folgendermaßen gestalten:
(Habe es einfach mal bei Header Top als HTML Element eingefügt)

```html
<span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-rss fa-stack-1x"></i>
</span>

<span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-search fa-stack-1x"></i>
</span>

```

Vielleicht hat ja noch jemand eine Idee wie man die Doppelten Icons am einfachsten Verlinken und noch ausrichten kann.

**Comment by Aybee** [comment]
> Wenn Du willst hau ich es noch ins ER2 ?

Kannste gerne machen.

Hast du mal einen Link, dass man sich ansehen kann, was du machst?

Ohne das jetzt kontrollieren zu können müsste das bereinigt von der Logik her eigentlich so aussehen:
```css
.toggler:after {
  width: 20px;
  height: 20px;
  min-height: 20px; /* überflüssig wegen height:20px; */
  right: 10px; /* dürfte hier nicht greifen, da weder relative noch absolute positioniert */
  float: right;
  display: inline-block; /* überflüssig wegen float:right;, hat dadurch automatisch display:block; */
  background-position: center;
  background-repeat: no-repeat;
  font: 20px FontAwesome;
  font-weight: bold;
  text-indent: -9999em;
  content: "\f13a";
  fontcolor: $basecolor; /* fontcolor? ist doch keine Eigenschaft. Meinst du color? */
}
.toggler.ui-state-active:after {
  content: "\f139";
  text-indent: 8px;
}

```
Für Lupe und RSS, kann man das nicht auch mit before und after machen? Braucht man dort extra leeres Markup?

**Comment by ciaobello** [comment]
ok >> ciaobello.luciano.ch

login:  see nickname
pw :    preview2015

Habe noch gesehen, wenn man fontawesome Erweiterung (siehe oben) installiert, kann man die Icons damit anzeigen im BE (Usereinstellungen, fontawesome verwenden). Ich spiele dann damit noch rum um Herauszufinden wie man das am einfachsten anwendet/einbindet.

Hast natürlich recht mit den Bemerkungen im CSS. Habe alles angepasst wie Du erwähnt hast. Da waren vorher Bilder deshalb wohl auch die anderen Eigenschaften. Bei der Farbe wird jetzt die genommen von der Schriftfarbe - Überschrift Accordeon.

Lupe und RSS gibt es nicht vierekig, dass sind einzelne Symbole die ich übereinander lege.
http://fortawesome.github.io/Font-Awesome/examples/  >> stacked icons

**Comment by Aybee** [comment]
Hier ein CSS um die Lupe und RSS mit Font Awesome nachzubilden. Extra Markup benötigt es nicht. Vorher das Bild beim Formular und RSS-Link entfernen. Aber ich weiß nicht, ob wir deswegen extra Font Awesome integrieren sollen. Vielleicht kann man auch einen Sprite mit schönen neutralen Icons anfertigen und davon die Icons abgreifen. Rahmen und Hintergrund kann man dann ja mit CSS machen. Außerdem werden diese Font Awesome Icons in meinem FF irgendwie unsauber gerendert.
```css
.rss {
  float: right;
  width: 24px;
  height: 24px;
  margin-left: 15px;
}
.rss a {
  display: block;
  width: 22px;
  height: 0;
  position: relative;
  border: 1px solid;
  background-color: burlywood;
  padding-top: 22px;
}
.rss a:before {
  content: "\f09e";
  font-family: FontAwesome;
  font-size: 16px;
  width: 22px;
  height: 22px;
  position: absolute;
  left: 3px;
  top: 1px;
}

.form-search div.submit_container {
  position: relative;
  border: 1px solid;
  margin: 0;
  padding: 0;
  overflow: hidden;
  width: 22px;
  height: 22px;
  background-color: burlywood;
}
.form-search div.submit_container:before {
  content: "\f002";
  font-family: FontAwesome;
  font-size: 16px;
  width: 22px;
  height: 22px;
  position: absolute;
  left: 3px;
  top: 1px;
}
.form-search .submit {
  padding: 0;
  width: 22px;
  height: 0;
  border: 0 none;
  background: transparent;
  padding-top: 22px;
  position: relative;
  cursor: pointer;
}
```
