### ISSUE TITLE
Formular Issues

### ISSUE THREAD

**Issue by Aybee** [contao/official-demo#7]
- [x] Es fehlt noch ein subtiler hover effekt auf submit buttons.
- [x] Cursor pointer für labels fehlt noch.
- [x] Formularfelder Hintergrundfarben vertauschen wegen Kontrast. Besser das aktive Feld hell gestalten.
- [x] Hover Effekt fehlt noch (nicht zwingend). Focus und active sind schon vorhanden.

user.html
login-34.html
- [x] Border sieht komisch aus, ist wahrscheinlich so nicht gewollt, hängt auch einmal über dem Passwort Feld und auf der Login Seite auch über dem Passwort Feld.
  https://github.com/may17/contao-demo/issues/13

``` css
#main .formbody div.submit_container {
  border-top: 1px dotted #D0C9C2;
  margin-top: 10px;
  padding-top: 20px;
}
```
